name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      run: |
        python -c "import streamlit; import pandas; import plotly; print('All imports successful')"
    
    - name: List files in the directory  # List files to verify correct path
      run: |
        ls -R
        echo "Listing all files to confirm the correct path to dashboard.py"
    
    - name: Validate Streamlit app  # Validate Streamlit app
      run: |
        streamlit run ./AI-Project/koenig-accountant/Salary-Management-Agent --server.headless true &
        sleep 10
        pkill -f streamlit
        echo "Streamlit app validation complete"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy notification
      run: echo "Ready for Streamlit Cloud deployment"
